# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200523_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Location'),
        ),
    ]
