# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200526_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
